# Docker Compose Configuration
version: '3.8'

services:
  backend:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8001:8001"
    environment:
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - LLAMA_API_KEY=${LLAMA_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ../backend:/app
    env_file:
      - ../backend/.env

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend